site_name: compiladores-g6-t01

theme:
    name: material

markdown_extensions:
    - pymdownx.arithmatex:
          generic: true

extra_javascript:
    - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js

nav:
    - Início: index.md
    - Visão Geral:
          - Descrição Compilador para C-- Strict para x86-64: descricao_compilador.md
          - Descrição da lógica de programação do C-- Strict: logica_programacao.md
          - Arquitetura Técnica e Regras de Escopo: arquitetura_escopo.md
    - Fases do Compilador:
          - Análise Léxica (tokens da linguagem): tokens.md
          - Funcionamento do Analisador Sintático: funcionamento_parser.md
          - Análise Sintática (gramática em BNF): Gramática.md
          - Restrições da Linguagem para Parsing: limitacoes_gramatica.md
          - Geração de Código Intermediário (C-- Strict para TAC): conversao_tac.md
          - Geração de Código Final (TAC para Assembly): conversao_assembly.md
    - Projeto e Processo:
          - Descrição das ferramentas: ferramentas.md
          - Descrição do setup do projeto: setup_compilador.md
          - Integração Contínua (CI): integracao_continua.md
          - Documento de padrão de commit (Angular): padrao_commit.md
    - Implementação:
          - Análise Léxica: implementacao_analise_lexica.md
          - Análise Sintática: implementacao_analise_sintatica.md
          - Geração de Código Intermediário: implementacao_conversao_tac.md
          - Geração de Código Final: implementacao_conversao_assembly.md
    - Testes:
          - Relatório Geral de Testes: relatorio_testes.md
          - Relatório de Testes Sintáticos: relatorio_testes_sintaticos.md
          - Testes de Análise Léxica: testes_analise_lexica.md
          - Testes de Análise Sintática: testes_analise_sintatica.md
          - Testes de Geração de Código Intermediário: testes_conversao_tac.md
          - Testes de Geração de Código Final: testes_conversao_assembly.md
    - Notas de estudo:
          - 1. Capítulo – Definição Formal da gramática livre de contexto: notas_estudo_1.md